name: CSV Formatting Validation

on:
  pull_request:
    paths:
      - "project-maintainers.csv"

jobs:
  validate-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate CSV
        uses: krook/csv-lint@main
        env:
          CSV_FILE: "project-maintainers.csv"
