# Used to validate changes to the project-maintainers.csv file
# Source: https://github.com/krook/csv-lint
# Test:   https://github.com/krook/csv-lint-test

on: [pull_request]

jobs:
  verify-cvs-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate CSV
        uses: krook/csv-lint@main
        env:
          CSV_FILE: "file.csv"
